JapanoriSystem/Controllers/FuncionarioController.cs
using JapanoriSystem.DAL;
using JapanoriSystem.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace JapanoriSystem.Controllers
{
    public class FuncionarioController : Controller
    {
        private bdJapanoriContext db = new bdJapanoriContext();

        // GET: Funcionario
        public ActionResult Index()
        {
            return View(db.tbFuncionario.ToList());
        }

        // GET: Funcionario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.tbFuncionario.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        // GET: Funcionario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Funcionario/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FuncionarioID,Nome,Sobrenome,DataNasc,Cargo,CPF,Endereco,NumeroEnd,Cep,DataContratacao,EmailCorp,Senha,Perm,cStatus")] Funcionario funcionario)
        {
            
                db.tbFuncionario.Add(funcionario);
                db.SaveChanges();
                return RedirectToAction("Index");
           

            //return View(funcionario);
        }

        // GET: Funcionario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.tbFuncionario.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        // POST: Funcionario/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FuncionarioID,Nome,Sobrenome,Cargo,CPF,Endereco,Cep,DataContratacao,EmailCorp,Senha,Perm,cStatus")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(funcionario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

        // GET: Funcionario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.tbFuncionario.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        // POST: Funcionario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Funcionario funcionario = db.tbFuncionario.Find(id);
            db.tbFuncionario.Remove(funcionario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JapanoriSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Japanori</title>
    <link rel="stylesheet" href="~/Content/themes/base/jquery-ui.css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!--link href="~/Content/chosen.min.css" rel="stylesheet" /-->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                @Html.ActionLink("JAPANORI", "Inicio", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (!(Session["usuarioLogado"] == null) || !(Session["senhaLogado"] == null))
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <img style="margin-top: 2px; width: 44px; height: 44px;" class="logo-japa" src="~/Source/Logo-japa.png" />
                        </li>
                        <li>@Html.ActionLink("Início", "Inicio", "Home")</li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Cadastros
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">

                                <li>@Html.ActionLink("Produto", "Create", "Produto")</li>
                                <li>@Html.ActionLink("Funcionário", "Create", "Funcionario")</li>
                                <li>@Html.ActionLink("Comanda", "Create", "Comanda")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Consultar
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">

                                <li>@Html.ActionLink("Produtos", "Index", "Produto")</li>
                                <li>@Html.ActionLink("Funcionários", "Index", "Funcionario")</li>
                                <li>@Html.ActionLink("Comandas", "Index", "Comanda")</li>

                            </ul>
                        </li>

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Comanda
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Inserir", "Inserir", "Comanda")</li>
                                <li>@Html.ActionLink("Consultar", "Index", "Comanda")</li>
                            </ul>
                        </li>
                        <li>
                            @Html.ActionLink("Vendas", "Index", "Vendas")
                        </li>
                        <li>
                            @Html.ActionLink("Caixa", "CaixaIDComanda", "Caixa")
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Configurações
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Perfil","Perfil","Conta")</li>
                                <li>@Html.ActionLink("Sair", "Logout", "Conta")</li>

                            </ul>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "Conta")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content" style="width:80%;">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

    <!--script src="~/Scripts/chosen.jquery.min.js"></!-script-->
</body>
</html>